# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

try_eval_tracer <- function(env) {
    invisible(.Call('testr_try_eval_tracer', PACKAGE = 'testr', env))
}

WriteCapInfo_cpp <- function(fname, args_env) {
    invisible(.Call('testr_WriteCapInfo_cpp', PACKAGE = 'testr', fname, args_env))
}

